using System.Collections.Generic;
using UnityEngine;

public class ConsoleFormat : MonoBehaviour {
    protected List<string> m_DefaultConsoleMessages = new List<string>() {"\r\n",
    "\r\n",
    "       　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　■■■　　■■■　　■■■　　■■■■　　■■■■■■　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　       　\r\n",
    "      　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　■　　　■　　■　　　　■　　■　　　　■　　■　　　　■　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　       　\r\n",
    "     　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　■　　　　　　■　　　　■　■　　　　　　■　■　　　　■　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　       　\r\n",
    "    　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　■■　　　　■■■■■■　■　　　　　　■　■　　　　■　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　       　\r\n",
    "   　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　■　　　■　　　　■　■　　　　　　■　■■■■■　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　       　\r\n",
    "  　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　■　　■　　　　■　■　　　　　　■　■　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　       　\r\n",
    " 　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　■　　　■　　■　　　　■　　■　　　　■　　■　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　       　\r\n",
    "　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　■■■■　　■■■　　■■■　　■■■■　　■■■　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　       　\r\n",
    "\r\n",
    "　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　ReRoll：cost      token\r\n",
    "<color=\"orange\">　　　　　　　　　＋──────────────＋　　　　　＋──────────────＋　　　　　＋──────────────＋　　　　　＋──────────────＋\r\n",
    "　　　　　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│\r\n",
    "　　　　　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│\r\n",
    "　　　　　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│\r\n",
    "　　　　　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│\r\n",
    "　　　　　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│\r\n",
    "　　　　　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│\r\n",
    "　　　　　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│\r\n",
    "　　　　　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│\r\n",
    "　　　　　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│\r\n",
    "　　　　　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│\r\n",
    "　　　　　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│\r\n",
    "　　　　　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│\r\n",
    "　　　　　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│\r\n",
    "　　　　　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│\r\n",
    "　　　　　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│　　　　　│<color=\"white\">　　　　　　　　　　　　　　</color>│\r\n",
    "　　　　　　　　　＋──────────────＋　　　　　＋──────────────＋　　　　　＋──────────────＋　　　　　＋──────────────＋</color>\r\n",
    "\r\n",
    "\r\n",
    "　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　＋────────────＋　　　　　　　＋────────────＋\r\n",
    "　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　｜　　　　リロール　　　　｜　　　　　　　｜　　　ステージ選択　　　｜\r\n",
    "　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　＋────────────＋　　　　　　　＋────────────＋\r\n",
    "\r\n",
    "\r\n",
    "\r\n",
    };


    protected readonly Dictionary<string, List<string>> m_abnoemalShopText = new Dictionary<string, List<string>>()
    {
        { "AttackSpeedStatic", new List<string>() {
        "　　　　　　　　　　　　　　",
        "　アタックスピード静的化　　",
        "　　　　　　　　　　　　　　",
        "現在のアタックスピード　　　",
        "カードを０枚にします。　　　",
        "獲得した倍率は残り、さらなる",
        "強化が可能になります。　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",}
        },
        { "AttackPowerStatic", new List<string>() {
        "　　　　　　　　　　　　　　",
        "　　アタックパワー静的化　　",
        "　　　　　　　　　　　　　　",
        "現在のアタックパワーカードを",
        "０枚にします。　　　　　　　",
        "獲得した倍率は残り、さらなる",
        "強化が可能になります。　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　", }
        },
        { "MoveSpeedStatic", new List<string>(){
        "　　　　　　　　　　　　　　",
        "　　ムーブスピード静的化　　",
        "　　　　　　　　　　　　　　",
        "現在のムーブスピードカードを",
        "０枚にします。　　　　　　　",
        "獲得した倍率は残り、さらなる",
        "強化が可能になります。　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",}
        },
        { "RangeStatic", new List<string>(){
        "　　　　　　　　　　　　　　",
        "　　　　レンジ静的化　　　　",
        "　　　　　　　　　　　　　　",
        "現在のレンジカードを０枚に　",
        "します。　　　　　　　　　　",
        "獲得した倍率は残り、さらなる",
        "る強化が可能になります。　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",}
        },
        { "MaxHPStatic", new List<string>(){
        "　　　　　　　　　　　　　　",
        "　　　最大体力静的化　　　　",
        "　　　　　　　　　　　　　　",
        "現在の最大体力カードを０枚に",
        "します。　　　　　　　　　　",
        "獲得した倍率は残り、さらなる",
        "強化が可能になります。　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",}
        },
        { "KnockbackStatic", new List<string>(){
        "　　　　　　　　　　　　　　",
        "　　ノックバック静的化　　　",
        "　　　　　　　　　　　　　　",
        "現在のノックバックカードを　",
        "０枚にします。　　　　　　　",
        "獲得した倍率は残り、さらなる",
        "強化が可能になります。　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",}
        },
        { "GetCoinStatic", new List<string>(){
        "　　　　　　　　　　　　　　",
        "　　　獲得コイン静的化　　　",
        "　　　　　　　　　　　　　　",
        "現在の獲得コインカードを　　",
        "０枚にします。　　　　　　　",
        "獲得した倍率は残り、さらなる",
        "強化が可能になります。　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",}
        },
        { "ShopPriceStatic", new List<string>(){
        "　　　　　　　　　　　　　　",
        "　　ショップ価格静的化　　　",
        "　　　　　　　　　　　　　　",
        "現在のショップ価格カードを　",
        "０枚にします。　　　　　　　",
        "獲得した倍率は残り、さらなる",
        "強化が可能になります。　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",}
        },
        { "ReRollPriceStatic", new List<string>(){
        "　　　　　　　　　　　　　　",
        "　　リロール価格静的化　　　",
        "　　　　　　　　　　　　　　",
        "現在のリロール価格カードを　",
        "０枚にします。　　　　　　　",
        "獲得した倍率は残り、さらなる",
        "強化が可能になります。　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",}
        },
        { "TimeLimitStatic", new List<string>(){
        "　　　　　　　　　　　　　　",
        "　　　制限時間静的化　　　　",
        "　　　　　　　　　　　　　　",
        "現在の制限時間カードを０枚に",
        "します。　　　　　　　　　　",
        "獲得した倍率は残り、さらなる",
        "強化が可能になります。　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",}
        },
        { "GetToken", new List<string>(){
        "　　　　　　　　　　　　　　",
        "　　　獲得トークン増加　　　",
        "　　　　　　　　　　　　　　",
        "獲得できるトークン量が　　　",
        "増加します。　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",
        "　　　　　　　　　　　　　　",}
        },
    };
}